- hosts: servers
  become: yes
  tasks:
    - name: Update apt package cache (for Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install GCC compiler
      ansible.builtin.package:
        name: 
          - gcc 
          - make
          - zip
          - unzip
          - screen
          - tmux
          - curl
          - wget
          - libmagickwand-dev
        state: present

