- hosts: servers
  become: yes
  vars:
    username: ******
    password: "{{ '*******' | password_hash('sha512') }}"
    public_key: "{{ lookup('file', '**********') }}"
    user_shell: /bin/bash
  tasks:
    - name: Create a new user
      user:
        name: "{{ username }}"
        password: "{{ password }}"
        groups: sudo
        append: yes
        shell: "{{ user_shell }}"
        create_home: yes

    - name: Set up authorized keys for the new user
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ public_key }}"

