- hosts: servers
  become: yes
  tasks:
    - name: Create systemd service unit for NVIDIA Persistence Daemon
      copy:
        dest: /etc/systemd/system/nvidia-persistenced.service
        content: |
          [Unit]
          Description=NVIDIA Persistence Daemon
          Wants=syslog.target

          [Service]
          Type=forking
          ExecStart=/usr/bin/nvidia-persistenced 
          ExecStop=/bin/kill -s TERM $MAINPID

          [Install]
          WantedBy=multi-user.target

      notify:
        - Reload systemd
        - Start and enable nvidia-persistenced

  handlers:
    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Start and enable nvidia-persistenced
      systemd:
        name: nvidia-persistenced
        state: started
        enabled: yes

